'use client';
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {peso} from "@/lib/utils";
import type {BookingDraft,Service} from "@/lib/types";

export default function BookingForm({services,promos,settings}:{services:Service[],promos:any[],settings:Record<string,string>}){
 const router=useRouter(); const [selected,setSelected]=useState<Record<string,string>>({}); const [files,setFiles]=useState<File[]>([]); const [form,setForm]=useState({customer_name:"",mobile_number:"",social_handle:"",preferred_date:"",preferred_time:"",removal:"None",promo_id:"",notes:"",terms_accepted:false}); const [busy,setBusy]=useState(false); const [err,setErr]=useState("");
 const items=useMemo(()=>services.filter(s=>selected[s.id]!==undefined).map(s=>{const v=s.service_variations?.find(x=>x.id===selected[s.id]); return {service_id:s.id,service_name:s.name,variation_id:v?.id,variation_name:v?.name,price:s.price+(v?.price_delta||0),duration_minutes:s.duration_minutes+(v?.duration_delta_minutes||0)}}),[services,selected]);
 const total=items.reduce((a,b)=>a+b.price,0);
 const toggle=(id:string)=>setSelected(x=>{const n={...x}; if(n[id]!==undefined)delete n[id]; else n[id]=""; return n});
 const submit=async()=>{setErr(""); if(!items.length)return setErr("Please select at least one service."); if(!form.customer_name||!form.mobile_number||!form.preferred_date||!form.preferred_time)return setErr("Please complete the required customer and appointment fields."); if(!form.terms_accepted)return setErr("Please agree to the Terms & Conditions."); setBusy(true);
   try{const data=new FormData(); data.append("payload",JSON.stringify({...form,services:items,inspiration_files:files.map(f=>f.name)})); files.forEach(f=>data.append("inspiration",f)); const r=await fetch("/api/bookings",{method:"POST",body:data}); const j=await r.json(); if(!r.ok)throw new Error(j.error||"Unable to submit request."); router.push(`/book/review?token=${j.token}`)}catch(e:any){setErr(e.message)}finally{setBusy(false)}
 };
 return <div className="form-layout"><div className="form-card">
  <h2 className="serif">1. Services</h2><div className="service-select">{services.map(s=><div className="service-row" key={s.id}><div className="service-top"><input type="checkbox" checked={selected[s.id]!==undefined} onChange={()=>toggle(s.id)}/><div><strong>{s.name}</strong><div className="muted">{s.description}</div></div><div>{peso(s.price)}</div></div>{selected[s.id]!==undefined&&<select value={selected[s.id]} onChange={e=>setSelected(x=>({...x,[s.id]:e.target.value}))}><option value="">Standard</option>{s.service_variations?.filter(v=>v.active).sort((a,b)=>a.sort_order-b.sort_order).map(v=><option value={v.id} key={v.id}>{v.name} {v.price_delta>=0?`(+${peso(v.price_delta)})`:`(${peso(v.price_delta)})`}</option>)}</select>}</div>)}</div>
  <h2 className="serif" style={{marginTop:35}}>2. Your details</h2>
  <div className="field"><label>Your Name *</label><input value={form.customer_name} onChange={e=>setForm({...form,customer_name:e.target.value})}/></div>
  <div className="field"><label>Mobile Number *</label><input inputMode="tel" value={form.mobile_number} onChange={e=>setForm({...form,mobile_number:e.target.value})}/></div>
  <div className="field"><label>IG or Messenger Handle</label><input value={form.social_handle} onChange={e=>setForm({...form,social_handle:e.target.value})}/></div>
  <h2 className="serif" style={{marginTop:35}}>3. Appointment</h2><div className="inline-grid"><div className="field"><label>Preferred Date *</label><input type="date" value={form.preferred_date} min={new Date().toISOString().slice(0,10)} onChange={e=>setForm({...form,preferred_date:e.target.value})}/></div><div className="field"><label>Preferred Time *</label><input type="time" value={form.preferred_time} onChange={e=>setForm({...form,preferred_time:e.target.value})}/></div></div>
  <div className="notice">Availability is flexible and owner-approved. Your selected date/time is a request, not a confirmed slot.</div>
  <h2 className="serif" style={{marginTop:35}}>4. Removal</h2><div className="field"><select value={form.removal} onChange={e=>setForm({...form,removal:e.target.value})}>{(settings.removal_options||"None\nGel\nSoft Gel\nHard Gel\nOther").split("\n").map(x=><option key={x}>{x}</option>)}</select></div>
  <h2 className="serif" style={{marginTop:35}}>5. Promo / Discount</h2><div className="field"><select value={form.promo_id} onChange={e=>setForm({...form,promo_id:e.target.value})}><option value="">No promo</option>{promos.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></div>
  <h2 className="serif" style={{marginTop:35}}>6. Nail Inspiration</h2><div className="field"><label>Nail Inspiration — File Upload</label><div className="upload"><input type="file" multiple accept=".jpg,.jpeg,.png,.heic,image/jpeg,image/png" onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,8))}/><div className="muted" style={{marginTop:8}}>{files.length?`${files.length} file(s) selected`:"JPG, JPEG, PNG; HEIC where supported."}</div></div></div>
  <h2 className="serif" style={{marginTop:35}}>7. Additional Requests / Notes</h2><div className="field"><textarea placeholder="Anything else you'd like us to know?" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div>
  <h2 className="serif" style={{marginTop:35}}>Terms & Conditions</h2><div className="terms">{settings.terms||"Down payment, rescheduling, lateness, cancellation, removal, warranty, home-based studio rules, payment rules, and photo/portfolio consent policies are configurable in Admin → Settings. Enter your exact existing Jotform policies before launch."}</div><label style={{display:"flex",gap:9,alignItems:"start",marginTop:14}}><input type="checkbox" checked={form.terms_accepted} onChange={e=>setForm({...form,terms_accepted:e.target.checked})}/><span>I have read and agree to The Claw Lab's Terms & Conditions.</span></label>
  {err&&<div className="notice" style={{marginTop:15}}>{err}</div>}<div style={{display:"flex",justifyContent:"flex-end",marginTop:22}}><button className="btn" disabled={busy} onClick={submit}>{busy?"Preparing…":"Review request →"}</button></div>
 </div><aside className="card" style={{position:"sticky",top:92}}><div className="kicker">Your request</div><h2 className="serif">Summary</h2>{items.length?items.map(x=><div key={x.service_id} style={{padding:"10px 0",borderBottom:"1px solid var(--line)"}}><strong>{x.service_name}</strong>{x.variation_name&&<div className="muted">{x.variation_name}</div>}<div>{peso(x.price)}</div></div>):<p className="muted">Choose services to see your request total.</p>}<div style={{display:"flex",justifyContent:"space-between",marginTop:15}}><strong>Estimated total</strong><strong>{peso(total)}</strong></div></aside></div>
}